# Run kohyli backend in dev mode (hot-reload)
run-dev:
    uv run fastapi dev

# Format project using experimental uv formatter (ruff)
format:
    uv format --preview-features format

# Run hurl-based API endpoint testing
test-api:
    hurl script/api.hurl

# Run pytest-based unit and integration tests
test:
    uv run pytest app/tests

# Generate a new alembic revision
migration-gen name:
    uv run alembic revision -m {{name}}

# Get latest alembic revision hash
migration-current:
    uv run alembic current

# Run an "up" migration - default target is latest (`+1`)
migration-up-head target="head":
    uv run alembic upgrade {{target}}

# Run a "down" migration - default target is the base (`-1`)
migration-down target="base":
    uv run alembic downgrade {{target}}

