# Run kohyli backend in dev mode (hot-reload)
run-dev:
    uv run fastapi dev

format:
    uv format --preview-features format

# Run hurl-based API endpoint testing
test-api:
    hurl script/api.hurl