[project]
name = "backend"
version = "0.1.0"
description = "Backend for the kohyli e-commerce website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi[standard]>=0.116.1",
    "greenlet>=3.2.4",
    "sqlmodel>=0.0.24",
]
