name: Hurl API Endpoint Test

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    test-api-endpoints:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          
        - name: Install uv
          uses: astral-sh/setup-uv@v6

        - name: Install the project dependencies
          run: uv suc --locked --all-extras --dev

        - name: Start the API server (background)
          run: |
            # Start server and capture logs
            uv run fastapi dev 2>&1
            echo $! > server.pid.txt
            echo "Server started with PID $(cat server.pid.txt)"

        - name: Install Hurl
          run: |
            sudo apt-add-repository ppa:lepapareil/hurl
            sudo apt install hurl="${VERSION}"*
          env:
            VERSION: '7.0.0'
        
        - name: Run Hurl tests
          run: hurl --test scripts/api.hurl
        
        - name: Show server log (on failure or success)
          if: always()
          run: |
            echo "Displaying server log:"
            cat server.log || echo "No log file found."

        - name: Stop the API server
          if: always()
          run: |
            if [ -f server.pid.txt ]; then
              kill $(cat server.pid.txt) || echo "Failed to kill process or process already stopped."
              rm server.pid.txt
            else
              echo "No PID file found, server may not have started."
            fi
